image: gradle:6.7-jdk15

stages:
  - build
  - staticAnalysis
  - test

variables:
  # Disable the Gradle daemon to ensure isolated runs of the CI pipeline.
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

build-event-microservice:
  stage: build
  script:
    gradle event-microservice:assemble event-microservice:testClasses

checkStyle-event-microservice:
  stage: staticAnalysis
  script:
    gradle event-microservice:checkstyleMain event-microservice:checkStyleTest
  allow_failure: true

PMD-event-microservice:
  stage: staticAnalysis
  script:
    gradle event-microservice:pmdMain
  allow_failure: true

test-event-microservice:
  stage: test
  script:
    - gradle event-microservice:test event-microservice:jacocoTestReport
    - cat event-microservice/build/reports/jacoco/test/html/index.html | grep -Po "Total.*?([0-9]{1,3})%"
  coverage: /([0-9]{1,3})%/
